### ISSUE TITLE
3.5.1-RC1 Omnibus target not booting on Fortinet F3+OSD V1 board

### ISSUE THREAD

**Issue by robertbailey** [ButterFlight/butterflight#106]
Updated to the RC and the FC became unresponsive, bridged boot pads to enable DFU and fell back to 3.5.0 with no problems, attempted 3.5.1 RC1 immediately again, and it again became unresponsive after the flash.

**Comment by AvaraKaisa** [comment]
Furibee Q95's omni f3 FC did same.

**Comment by kidBrazil** [comment]
Thanks guys, we are aware of the issue and working to fix it for the next RC

**Comment by adrianmiriuta** [comment]
same for 
LUXV2_RACE

**Comment by adrianmiriuta** [comment]
@apocolipse 
@kidBrazil 
@LexioTech 

I have tested this build  working (no boot hangup) on
 F4 (OMNIBUSF4DS)
 F7 (REVO)
that means it must be some processor bound problem that affects only the F3.

**Comment by SnappyFPV** [comment]
FF_PikoBlx same issue. Device not Found after flashing 3.5.1 RC

**Comment by robertbailey** [comment]
This issue has been resolved for me on 3.5.1-RC2 flashed onto Fortinet F3+OSD V1 board
