### ISSUE TITLE
MSP parsing

### ISSUE THREAD

**Issue by adrianmiriuta** [ButterFlight/butterflight#111]
debuging  values over MSP 
do not work any more 

# version
# ButterFlight / HELIOSPRING (HESP) 3.5.1 Apr 10 2018 / 21:13:41 (49c2ac986) MSP API: 1.40
# IMU-F Version: 106

# get debug_mode
debug_mode = NOTCH

![screenshot from 2018-04-12 15-18-55](https://user-images.githubusercontent.com/29194202/38679784-e59aeef4-3e64-11e8-863d-34fcfd1928af.png)

**Comment by orneryd** [comment]
fixed with https://github.com/ButterFlight/butterflight/pull/109

**Comment by orneryd** [comment]
![image](https://user-images.githubusercontent.com/1736223/38704167-546886a8-3e5a-11e8-87f7-c876cfe83200.png)
