### ISSUE TITLE
RC7-Caprica HELIOSPRING BBL does not show debug traces

### ISSUE THREAD

**Issue by adrianmiriuta** [ButterFlight/butterflight#115]
I tried
debug_mode=NOTCH
debug_mode=ANGLERATE
debug_mode=IMU
none works.

![screenshot from 2018-04-13 18-42-30](https://user-images.githubusercontent.com/29194202/38747224-78e8469e-3f4a-11e8-9e46-44457bfed8a8.png)

**Comment by orneryd** [comment]
There is no Notch so we should probably remove it from our target

IMU we could probably add logging the attitiude/quaternion values coming from IMUF.

**Comment by adrianmiriuta** [comment]
@orneryd 
I also tried debug_mode=ANGLERATE
it does not BBL , or MSP log either.

**Comment by adrianmiriuta** [comment]
@orneryd 
@rs2k 

correction
debug_mode=ANGLERATE works (my receiver was broken)

other debug_modes are not relevant on HELIOSPRING

**Comment by orneryd** [comment]
I think we are going to leave the additional modes there for potential future use, but just add some documentation stating they do not apply.
