### ISSUE TITLE
merge F7 optimization from betaflight 3.4

### ISSUE THREAD

**Issue by emski0** [ButterFlight/butterflight#122]
Hi
Is there plans soon to  bring the F7 optimization (from https://ci.betaflight.tech/job/Betaflight%20F7%20Optimizations/) to butterflight.
I am flying this build on Matek F7 and i am able to run 32k gyro /32k PID loop, with dynamic filter on and accelerometer on, and the cpu load is at 29%
While on butterflight i can only run 32k gyro /8k pid loop with over 85% cpu load.

Thanks

**Comment by orneryd** [comment]
this is coming after we finalize the release 3.5.1. I have already merged it up into the imuf_107_odin_bef_rebase branch
