### ISSUE TITLE
RC9-Caprica HELIOSPRING IMUF calibration issue

### ISSUE THREAD

**Issue by adrianmiriuta** [ButterFlight/butterflight#148]
@kidBrazil 
@orneryd 

Sometimes IMUF calibration seems to fail,
than all axes drift horrible.

**Comment by hansie79fpv** [comment]
Hi. Finished my chameleon build yesterday.
Setup. Chameleon, helio spring, 32/32 proshot bf 3.5.1 rc9 tekko32 on hypetrain v1.1. I expirenced the smae as you described. Just sometimes ranodmly when plugging in.
