### ISSUE TITLE
FPVM_BETAFLIGHT F7 second gyro won't work in 32khz mode

### ISSUE THREAD

**Issue by mmakam2** [ButterFlight/butterflight#157]
Hi, reporting the issue for this target (butterflight_3.5.1_FPVM_BETAFLIGHTF7.hex), 32khz mode won't work with gyro_to_use = 1 setting. On save/reboot it goes back to 8khz/8khz.

Betaflight 3.4 i am able to use 32khz mode, but only 32khz/16khz.

**Comment by orneryd** [comment]
this is coming after we finalize the release 3.5.1. I have already merged it up into the imuf_107_odin_bef_rebase branch
