### ISSUE TITLE
FC does not boot with old SDcard

### ISSUE THREAD

**Issue by 0crap** [ButterFlight/butterflight#164]
My Matek F405-STD flight controller simply does not boot with old SDcards inserted.
Tested with Butterflight 3.5.1 - RC2
SDcard works perfectly fine in other devices. (Cam, cellphone, etc.)

Same issue as https://github.com/betaflight/betaflight/issues/5303
Hope this can be looked at, or ported from BF when fixed.

**Comment by orneryd** [comment]
this is coming after we finalize the release 3.5.1. I have already merged it up into the imuf_107_odin_bef_rebase branch
