### ISSUE TITLE
Fport lua scripts not working. 

### ISSUE THREAD

**Issue by Surgikill** [ButterFlight/butterflight#187]
I am running the latest Fport beta firmware ver. 180615. I am running an R-XSR with a helio spring, using a Taranis x9d. Everything will work fine on this setup, except LUA. I get telemetry from the FC and I can send stick inputs, but the lua scripts will not populate. I just flashed the betaflight target 3.4.0-RC3 found here https://github.com/heliorc/imuf-release and the lua scripts will work fine with the FC running betaflight. I am using butterflight lua scripts, not betaflight. I believe this is a problem inherent to butterflight seeing as the exact same setup will work properly on betaflight.

**Comment by adrianmiriuta** [comment]
@Surgikill 
try flasing this image 
[butterflight_3.5.2_HELIOSPRING](http://silverbug.org/28.06.2018/butterflight_3.5.2_HELIOSPRING.hex) 
over a working and configured standard image 
[Butterflight_3.5.2_MSD_1.0.0_IMUF_1.0.7-ODIN](https://github.com/heliorc/imuf-release/blob/master/Butterflight_3.5.2_MSD_1.0.0_IMUF_1.0.7-ODIN.hex)

!!!! disable "Full chip erase"  when flashing the custom build !!!!

please update me if it works.

**Comment by Surgikill** [comment]
@adrianmiriuta Yes that works perfectly. The fields populate and the values that I change will save properly.

**Comment by kidBrazil** [comment]
@adrianmiriuta Thanks for looking into this

**Comment by adrianmiriuta** [comment]
@Surgikill 
@kidBrazil 
this was merged PR #184
you can close the issue .
