### ISSUE TITLE
Motolab tempest F4     Be sure to set tlm_halfduplex = on     It's set to off by default and your quad will not arm.

### ISSUE THREAD

**Issue by mtnmikev** [ButterFlight/butterflight#20]
Motolab Tempest bug with Telemetry Half Duplex

**Comment by mtnmikev** [comment]
Using crossfire for tx/rx

**Comment by kidBrazil** [comment]
Just waiting on @mtnmikev to confirm that the test hex I provided him indeed fixes his issue - Don't have Motolab Tempest F4 to test agains.

**Comment by kidBrazil** [comment]
@mtnmikev My friend, I am giving you until Monday to report back on this issue or we are going to close it.

**Comment by kidBrazil** [comment]
User gave up - no testing ever happened
