### ISSUE TITLE
No video selection tab in OSD menu

### ISSUE THREAD

**Issue by neverknownbetter** [ButterFlight/butterflight#37]
I'm unable to select the correct video output (auto/pal/nstc). The selection tab is not there. running a spracing F3 stacked with a spracing OSD. both flashed with 3.4.0 stable ok. 
![20180307_170115](https://user-images.githubusercontent.com/27512558/37108889-6cc4a07e-2230-11e8-82a7-03fdd3f3e5a1.jpg).
not listed in CLI
# get osd
osd_units = METRIC
Allowed values: IMPERIAL, METRIC

osd_warnings = 61
Allowed range: 0 - 32767

osd_rssi_alarm = 45
Allowed range: 0 - 100

osd_cap_alarm = 2200
Allowed range: 0 - 20000

osd_alt_alarm = 100
Allowed range: 0 - 10000

osd_ah_max_pit = 20
Allowed range: 0 - 90

osd_ah_max_rol = 40
Allowed range: 0 - 90

osd_tim1 = 2560
Allowed range: 0 - 32767

osd_tim2 = 2561
Allowed range: 0 - 32767

osd_vbat_pos = 2475
Allowed range: 0 - 3071

osd_rssi_pos = 2049
Allowed range: 0 - 3071

osd_tim_1_pos = 234
Allowed range: 0 - 3071

osd_tim_2_pos = 2487
Allowed range: 0 - 3071

osd_remaining_time_estimate_pos = 234
Allowed range: 0 - 3071

osd_flymode_pos = 2074
Allowed range: 0 - 3071

osd_throttle_pos = 234
Allowed range: 0 - 3071

osd_vtx_channel_pos = 234
Allowed range: 0 - 3071

osd_crosshairs = 234
Allowed range: 0 - 3071

osd_ah_sbar = 234
Allowed range: 0 - 3071

osd_ah_pos = 234
Allowed range: 0 - 3071

osd_current_pos = 234
Allowed range: 0 - 3071

osd_mah_drawn_pos = 234
Allowed range: 0 - 3071

osd_craft_name_pos = 234
Allowed range: 0 - 3071

osd_gps_speed_pos = 234
Allowed range: 0 - 3071

osd_gps_lon_pos = 234
Allowed range: 0 - 3071

osd_gps_lat_pos = 234
Allowed range: 0 - 3071

osd_gps_sats_pos = 234
Allowed range: 0 - 3071

osd_home_dir_pos = 234
Allowed range: 0 - 3071

osd_home_dist_pos = 234
Allowed range: 0 - 3071

osd_compass_bar_pos = 234
Allowed range: 0 - 3071

osd_altitude_pos = 2465
Allowed range: 0 - 3071

osd_pid_roll_pos = 234
Allowed range: 0 - 3071

osd_pid_pitch_pos = 234
Allowed range: 0 - 3071

osd_pid_yaw_pos = 234
Allowed range: 0 - 3071

osd_debug_pos = 234
Allowed range: 0 - 3071

osd_power_pos = 234
Allowed range: 0 - 3071

osd_pidrate_profile_pos = 234
Allowed range: 0 - 3071

osd_warnings_pos = 2377
Allowed range: 0 - 3071

osd_avg_cell_voltage_pos = 234
Allowed range: 0 - 3071

osd_pit_ang_pos = 234
Allowed range: 0 - 3071

osd_rol_ang_pos = 234
Allowed range: 0 - 3071

osd_battery_usage_pos = 234
Allowed range: 0 - 3071

osd_disarmed_pos = 234
Allowed range: 0 - 3071

osd_nheading_pos = 234
Allowed range: 0 - 3071

osd_nvario_pos = 234
Allowed range: 0 - 3071

osd_esc_tmp_pos = 234
Allowed range: 0 - 3071

osd_esc_rpm_pos = 234
Allowed range: 0 - 3071

osd_rtc_date_time_pos = 234
Allowed range: 0 - 3071

osd_adjustment_range_pos = 234
Allowed range: 0 - 3071

osd_core_temp_pos = 234
Allowed range: 0 - 3071

osd_stat_max_spd = OFF
Allowed values: OFF, ON

osd_stat_max_dist = OFF
Allowed values: OFF, ON

osd_stat_min_batt = ON
Allowed values: OFF, ON

osd_stat_min_rssi = ON
Allowed values: OFF, ON

osd_stat_max_curr = OFF
Allowed values: OFF, ON

osd_stat_used_mah = OFF
Allowed values: OFF, ON

osd_stat_max_alt = ON
Allowed values: OFF, ON

osd_stat_bbox = OFF
Allowed values: OFF, ON

osd_stat_endbatt = OFF
Allowed values: OFF, ON

osd_stat_bb_no = OFF
Allowed values: OFF, ON

osd_stat_rtc_date_time = OFF
Allowed values: OFF, ON

osd_stat_tim_1 = OFF
Allowed values: OFF, ON

osd_stat_tim_2 = ON
Allowed values: OFF, ON

**Comment by kidBrazil** [comment]
@neverknownbetter -I am closing this Issue because it is actually related to the Betaflight Configurator not the firmware. Could you please re-open the issue over on this URL? https://github.com/ButterFlight/butterflight-configurator/issues
