### ISSUE TITLE
Multishot causing motors to spin up 

### ISSUE THREAD

**Issue by MrNoizeFPV** [ButterFlight/butterflight#39]
so have an issue I usually run dshot but having some weird issues with it on hard front flips, so put multishot on plugged in the battery and 3 of the motors started spinning up slightly not enough to cut your fingers but sketchy enough that I had to put my foot on the quad to unplug it very dangerous im on the helio board as well have not had the issue on dshot

**Comment by flint723** [comment]
In Config tab change your "minimum command" under multishot to like 980 (or lower if you have to) instead of 1000.

**Comment by kidBrazil** [comment]
@MrNoizeFPV can you please try @flint723 suggestion and get back to us?

**Comment by papayou66** [comment]
@MrNoizeFPV did you calibrate your mutlishot from motor TAB ? 1000-2000

**Comment by MrNoizeFPV** [comment]
Hey guys sorry just seeing the mesages I lowered the command and that did it worked fine but Im seeing a weird what seems like a desync issue on dshot and multishot ive played with the idle values for both to see if that fixes it, but when I do a hard front flip the quad does not commit to the flip and kicks back im able to save it every time and it does not happen every time, part of me feels like it could be me when I flick the stick fast for the flip its like im bringing the stick back slightly and not committing its weird but I have had it happen on ms and dshot now. also wondering if its the loop speed running 16/16

**Comment by MrNoizeFPV** [comment]
papayou no I calibrated in blheli

**Comment by papayou66** [comment]
wich value ? and i think it's better to make a manual calibration from the GUI

**Comment by MrNoizeFPV** [comment]
papayou check my long message above i got it to work fine no more spinning motors my issue im having now is a weird one

**Comment by kidBrazil** [comment]
@MrNoizeFPV Can you record a BB of the weird issue and send it to us please?

**Comment by MrNoizeFPV** [comment]
@kidBrazil just sent you a bb in butter slack

**Comment by kidBrazil** [comment]
After reviewing @MrNoizeFPV it was found that he had RC Interpolation setup incorrectly and therefore there is no bug to be fixed.
