### ISSUE TITLE
Feature Request: Map radio auxiliary channel to general purpose output

### ISSUE THREAD

**Issue by totterfree** [ButterFlight/butterflight#53]
Problem:
   Our flight controllers don't have a way to communicate with "dumb" hardware. There is no software for controlling generic outputs on our flight controllers (like gpio on arduino). We have PWM, but there are many use cases which require a simple high/low state.

My Specific Use Case:
   I would like to be able to better control the on/off state of my video transmitters. Reason being, that I (and many others) need to be able to compete in team races where quads are not recoverable after crashing. Currently SA is not robust enough to be powered off on initial plugin, powered on via aux, and powered completely off in the event of a downed (but not unplugged) quad. In order to solve this, I would like to be able to switch the power to my VTX on and off via something like a transistor. The only problem is that I have no way (using cleanflight, betaflight, raceflight, or butterflight, or to do so.

Proposed Solution:
   I propose a generic purpose output resource which could be mapped to UART, buzzer, LED, etc in order to control such circuits. This is obviously dependent on if those pins are capable of outputs other than PWM.

Note:
   It's possible such functionality might also include generic purpose input as well, in which case we are really just talking about mapping a GPIO pin. Since this is not part of my use case I am not including it in this feature request, but it's worth considering from a developer standpoint.

**Comment by chriswils** [comment]
I second this. All pins that can do pwm can also output simple on/off (or just 0-100% duty cycle).

**Comment by joeostrander** [comment]
I think PinIO/PinioBox is in this fork -- I've been meaning to try it...
https://github.com/betaflight/betaflight/wiki/Pinio-and-PinioBox
https://github.com/betaflight/betaflight/issues/5338

**Comment by joeostrander** [comment]
FYI, I just tested PinIO and it worked great.

**Comment by totterfree** [comment]
@joeostrander that's good to hear! Now that's only indicating the current flight mode correct? Or is it something that can be mapped to an radio aux channel?

**Comment by joeostrander** [comment]
It maps to radio aux channel.  After entering CLI commands, you'll get new box(es) like *User 1* on the Modes tab.

**Comment by kidBrazil** [comment]
@totterfree is this issue then resolved by the pinIO?

**Comment by totterfree** [comment]
@kidBrazil It looks like it is indeed! I'd like to give this a test before saying it is for sure. Hopefully this week I can confirm. Is it likely that we could merge the IO code assuming the devs give it the thumbs up?

**Comment by kidBrazil** [comment]
@totterfree awesome man no problem at all. I see no reason why we cant merge it tho I am pretty sure it is already part of the codebase. Will check.

Cheers

**Comment by joeostrander** [comment]
I did my tests with Butterflight, I think it's all good :)

**Comment by kidBrazil** [comment]
Closing issue as it seems to be solved by existing pinIO interface.
