### ISSUE TITLE
FFPIKOBLX - Spektrum RX Not Working (BeF & BuF)

### ISSUE THREAD

**Issue by garyjohnmac** [ButterFlight/butterflight#56]
I flashed 100 flying egg to ffpikoblx but now the controller does not see the spectrum rx the rx light is on so it has linked to the tx .I tried all the ports with no help . On configuration screen the spektrum is set up as always . if i flash back the betaflight 3.2.4 all works but if i flash betaflight 3.3.0 same problem as butterflight 

EDIT: - for clarity - KidBrazil

**Comment by garyjohnmac** [comment]
Update
Flashed from butterflight back to betaflight 3.3.0 same problem spektrum orange led burns solid when link to the tx  but no connection to the bourd . flashed to betaflight 2,2,5 all works normally drones flyes .I flashed back to betaflight 3.3.0 problem back and same problem on butterflight so it cant be a hardware problem as it works on betaflight 2.2.5 
Has no one a solution to my problem

**Comment by kidBrazil** [comment]
@garyjohnmac - Does the port need to be inverted for spektrum?

**Comment by garyjohnmac** [comment]
Dont think so dont know of they have changed the ports but the port was always on UART3 did try all the ports with no success .
 Reciever mode is set as serial based Reciever (speksat,sbus,sumb)
Reciever provider  is set at spektrum 2048 as it is dsmx sat reciever 
Channel map is set as TAER 1234

**Comment by garyjohnmac** [comment]
Changed serialrx_inverted = on to set serialrx_inverted = OFF and that fixed the problem thanks all
