### ISSUE TITLE
F4 SD card logging

### ISSUE THREAD

**Issue by robert-b** [ButterFlight/butterflight#72]
sd card logging is broken on an spracingf4evo board.
might be broken on other boards as well.

**Comment by jstremmler** [comment]
Same on Omnibus F4... It logs but loggfile shows with blackbox logger Cleanflight 3.3.0 RC1 garbage only.

**Comment by robert-b** [comment]
jürgen,
take the betaflight chrome app.

i found some logs on the sd-card.
the issue can be closed.
