### ISSUE TITLE
pid setpoint calculation is wrong

### ISSUE THREAD

**Issue by robert-b** [ButterFlight/butterflight#73]
`    dtermSetpointWeight = pidProfile->dtermSetpointWeight / 127.0f;`

when using full, 100 % , dterm weighting weighting it is in the configurator displayed as 1.27
you should team up getting the calculus right ...

**Comment by kidBrazil** [comment]
@robert-b I am a bit confused here, you are saying that when you set Dterm setpoint weight to max value in configurator it gets displayed as 1.27? Where does that get displayed? UI?

**Comment by robert-b** [comment]
it is the slider in the pid tab.
setpoint weighting would be the english term.

**Comment by orneryd** [comment]
I think it's a display "feature" just like the pids and other values which are displayed differently and then scaled when used.
