### ISSUE TITLE
Fix: 3D flymode improvement

### ISSUE THREAD

**Issue by thongraegu** [ButterFlight/butterflight#86]
https://github.com/betaflight/betaflight/pull/5571

That PR Iw been testing, makes 3D mode fly just like it should, been testing it for a while. It doesnt affect/change anything on normal 2D side of things, just effects 3D. :)

**Comment by Teracis** [comment]
The PR referenced is just for testing via disabling the mixer gain halving using the cli variable. If it's found that the halving should be removed permanently the PR will need to be updated and merged into the master. Testing is still in progress, thanks for helping with the testing @thongraegu

**Comment by thongraegu** [comment]
Alright, this is the real deal fix

https://github.com/betaflight/betaflight/pull/5582

**Comment by varkokonyi** [comment]
Cherry-picked this commit over from BF, just for you @thongraegu

**Comment by Teracis** [comment]
It should help everyone who wants to fly 3D. I meant to get back here and reference it but glad you guys found it. I got to test it myself today and it's epic!

**Comment by varkokonyi** [comment]
I have seen the discussion on the BF repo and the issue and thought the BuF guys could use this
